variables:
  SSH_OPT: -o StrictHostKeyChecking=no

stages:
  - build
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - echo "$DEPLOY_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - docker login -u $LOGIN_REGISTRY -p $PASS_REGISTRY $REGISTRY_HOST || true
 
### common build
build:
  stage: build
  script:
    - docker build -t $REGISTRY_HOST/alternative-tms-front:$CI_PIPELINE_ID -f ./docker/front/Dockerfile .
    - docker push $REGISTRY_HOST/alternative-tms-front:$CI_PIPELINE_ID
    - docker build -t $REGISTRY_HOST/alternative-tms-tasks:$CI_PIPELINE_ID -f ./docker/tasks/Dockerfile .
    - docker push $REGISTRY_HOST/alternative-tms-tasks:$CI_PIPELINE_ID
    - docker build -t $REGISTRY_HOST/alternative-tms-back:$CI_PIPELINE_ID -f ./docker/back/Dockerfile .
    - docker push $REGISTRY_HOST/alternative-tms-back:$CI_PIPELINE_ID
  when: manual

#DEPLOY-DEMOPLUS

demoplus-with-drop-db:
  variables:
    SSH_USER:  server
    SSH_HOST:  10.10.5.3
    SSH_LINE: ssh $SSH_OPT $SSH_USER@$SSH_HOST
  stage: deploy
  script:
    - $SSH_LINE "docker login -u $LOGIN_REGISTRY -p $PASS_REGISTRY $REGISTRY_HOST || true"
    - $SSH_LINE "docker pull $REGISTRY_HOST/alternative-tms-back:$CI_PIPELINE_ID; docker pull $REGISTRY_HOST/alternative-tms-tasks:$CI_PIPELINE_ID; docker pull $REGISTRY_HOST/alternative-tms-front:$CI_PIPELINE_ID; cd /opt/alternative-tms ; docker-compose down ; sudo rm -Rf ./postgres_old ; sudo mv ./postgres ./postgres_old ; tag_of_image=$CI_PIPELINE_ID docker-compose -f docker-compose-template.yml up -d"
  when: manual

demoplus:
  variables:
    SSH_USER:  server
    SSH_HOST:  10.10.5.3
    SSH_LINE: ssh $SSH_OPT $SSH_USER@$SSH_HOST
  stage: deploy
  script:
    - $SSH_LINE "docker login -u $LOGIN_REGISTRY -p $PASS_REGISTRY $REGISTRY_HOST || true"
    - $SSH_LINE "docker pull $REGISTRY_HOST/alternative-tms-back:$CI_PIPELINE_ID; docker pull $REGISTRY_HOST/alternative-tms-tasks:$CI_PIPELINE_ID; docker pull $REGISTRY_HOST/alternative-tms-front:$CI_PIPELINE_ID; cd /opt/alternative-tms ; docker-compose down ; tag_of_image=$CI_PIPELINE_ID docker-compose -f docker-compose-template.yml up -d"
  when: manual
