using System;
using System.Data;
using ThinkingHome.Migrator.Framework;
using ThinkingHome.Migrator.Framework.Extensions;

namespace DAL.Migrations
{
    [Migration(201910140628)]
    public class AddCountries : Migration
    {
        public override void Apply()
        {
            Database.AddTable("Countries",
                new Column("Id", DbType.Guid, ColumnProperty.PrimaryKey),
                new Column("Key", DbType.String.WithSize(10)),
                new Column("Name", DbType.String.WithSize(255)));
            Database.AddIndex("Countries_ix", true, "Countries", "Key");

            AddCountry("AD", "Andorra");
            AddCountry("AE", "Utd. Arab Emir.");
            AddCountry("AF", "Afghanistan");
            AddCountry("AG", "Antigua/Barbads");
            AddCountry("AI", "Anguilla");
            AddCountry("AL", "Albania");
            AddCountry("AM", "Armenia");
            AddCountry("AN", "Dutch Antilles");
            AddCountry("AO", "Angola");
            AddCountry("AQ", "Antarctica");
            AddCountry("AR", "Argentina");
            AddCountry("AS", "Samoa,American");
            AddCountry("AT", "Austria");
            AddCountry("AU", "Australia");
            AddCountry("AW", "Aruba");
            AddCountry("AZ", "Azerbaijan");
            AddCountry("BA", "Bosnia-Herz.");
            AddCountry("BB", "Barbados");
            AddCountry("BD", "Bangladesh");
            AddCountry("BE", "Belgium");
            AddCountry("BF", "Burkina-Faso");
            AddCountry("BG", "Bulgaria");
            AddCountry("BH", "Bahrain");
            AddCountry("BI", "Burundi");
            AddCountry("BJ", "Benin");
            AddCountry("BM", "Bermuda");
            AddCountry("BN", "Brunei Dar-es-S");
            AddCountry("BO", "Bolivia");
            AddCountry("BR", "Brazil");
            AddCountry("BS", "Bahamas");
            AddCountry("BT", "Bhutan");
            AddCountry("BV", "Bouvet Island");
            AddCountry("BW", "Botswana");
            AddCountry("BY", "White Russia");
            AddCountry("BZ", "Belize");
            AddCountry("CA", "Canada");
            AddCountry("CC", "Coconut Islands");
            AddCountry("CD", "Dem. Rep. Congo");
            AddCountry("CF", "Central Afr.Rep");
            AddCountry("CG", "Rep.of Congo");
            AddCountry("CH", "Switzerland");
            AddCountry("CI", "Ivory Coast");
            AddCountry("CK", "Cook Islands");
            AddCountry("CL", "Chile");
            AddCountry("CM", "Cameroon");
            AddCountry("CN", "China");
            AddCountry("CO", "Colombia");
            AddCountry("CR", "Costa Rica");
            AddCountry("CS", "Serbia/Monten.");
            AddCountry("CU", "Cuba");
            AddCountry("CV", "Cape Verde");
            AddCountry("CX", "Christmas Islnd");
            AddCountry("CY", "Cyprus");
            AddCountry("CZ", "Czech Republic");
            AddCountry("DB", "Dubai");
            AddCountry("DE", "Germany");
            AddCountry("DJ", "Djibouti");
            AddCountry("DK", "Denmark");
            AddCountry("DM", "Dominica");
            AddCountry("DO", "Dominican Rep.");
            AddCountry("DZ", "Algeria");
            AddCountry("EC", "Ecuador");
            AddCountry("EE", "Estonia");
            AddCountry("EG", "Egypt");
            AddCountry("ER", "Eritrea");
            AddCountry("ES", "Spain");
            AddCountry("ET", "Ethiopia");
            AddCountry("FI", "Finland");
            AddCountry("FJ", "Fiji");
            AddCountry("FK", "Falkland Islnds");
            AddCountry("FM", "Micronesia");
            AddCountry("FO", "Faeroe");
            AddCountry("FR", "France");
            AddCountry("GA", "Gabon");
            AddCountry("GB", "United Kingdom");
            AddCountry("GD", "Grenada");
            AddCountry("GE", "Georgia");
            AddCountry("GF", "French Guinea");
            AddCountry("GG", "Guernsey");
            AddCountry("GH", "Ghana");
            AddCountry("GI", "Gibraltar");
            AddCountry("GL", "Greenland");
            AddCountry("GM", "Gambia");
            AddCountry("GN", "Guinea");
            AddCountry("GP", "Guadeloupe");
            AddCountry("GQ", "Equatorial Guin");
            AddCountry("GR", "Greece");
            AddCountry("GS", "S. Sandwich Ins");
            AddCountry("GT", "Guatemala");
            AddCountry("GU", "Guam");
            AddCountry("GW", "Guinea-Bissau");
            AddCountry("GY", "Guyana");
            AddCountry("HK", "Hong Kong");
            AddCountry("HM", "Heard/McDon.Isl");
            AddCountry("HN", "Honduras");
            AddCountry("HR", "Croatia");
            AddCountry("HT", "Haiti");
            AddCountry("HU", "Hungary");
            AddCountry("ID", "Indonesia");
            AddCountry("IE", "Ireland");
            AddCountry("IL", "Israel");
            AddCountry("IM", "Isle of Man");
            AddCountry("IN", "India");
            AddCountry("IO", "Brit.Ind.Oc.Ter");
            AddCountry("IQ", "Iraq");
            AddCountry("IR", "Iran");
            AddCountry("IS", "Iceland");
            AddCountry("IT", "Italy");
            AddCountry("JE", "Jersey");
            AddCountry("JM", "Jamaica");
            AddCountry("JO", "Jordan");
            AddCountry("JP", "Japan");
            AddCountry("KE", "Kenya");
            AddCountry("KG", "Kirghistan");
            AddCountry("KH", "Cambodia");
            AddCountry("KI", "Kiribati");
            AddCountry("KM", "Comoro");
            AddCountry("KN", "St.Chr.,Nevis");
            AddCountry("KP", "North Korea");
            AddCountry("KR", "South Korea");
            AddCountry("KW", "Kuwait");
            AddCountry("KY", "Cayman Islands");
            AddCountry("KZ", "Kazakhstan");
            AddCountry("LA", "Laos");
            AddCountry("LB", "Lebanon");
            AddCountry("LC", "St. Lucia");
            AddCountry("LI", "Liechtenstein");
            AddCountry("LK", "Sri Lanka");
            AddCountry("LR", "Liberia");
            AddCountry("LS", "Lesotho");
            AddCountry("LT", "Lithuania");
            AddCountry("LU", "Luxembourg");
            AddCountry("LV", "Latvia");
            AddCountry("LY", "Libya");
            AddCountry("MA", "Morocco");
            AddCountry("MC", "Monaco");
            AddCountry("MD", "Moldavia");
            AddCountry("ME", "Montenegro");
            AddCountry("MG", "Madagascar");
            AddCountry("MH", "Marshall Islnds");
            AddCountry("MK", "North Macedonia");
            AddCountry("ML", "Mali");
            AddCountry("MM", "Myanmar");
            AddCountry("MN", "Mongolia");
            AddCountry("MO", "Macau");
            AddCountry("MP", "N.Mariana Islnd");
            AddCountry("MQ", "Martinique");
            AddCountry("MR", "Mauretania");
            AddCountry("MS", "Montserrat");
            AddCountry("MT", "Malta");
            AddCountry("MU", "Mauritius");
            AddCountry("MV", "Maldives");
            AddCountry("MW", "Malawi");
            AddCountry("MX", "Mexico");
            AddCountry("MY", "Malaysia");
            AddCountry("MZ", "Mozambique");
            AddCountry("NA", "Namibia");
            AddCountry("NC", "New Caledonia");
            AddCountry("NE", "Niger");
            AddCountry("NF", "Norfolk Island");
            AddCountry("NG", "Nigeria");
            AddCountry("NI", "Nicaragua");
            AddCountry("NL", "Netherlands");
            AddCountry("NO", "Norway");
            AddCountry("NP", "Nepal");
            AddCountry("NR", "Nauru");
            AddCountry("NU", "Niue Islands");
            AddCountry("NZ", "New Zealand");
            AddCountry("OM", "Oman");
            AddCountry("PA", "Panama");
            AddCountry("PE", "Peru");
            AddCountry("PF", "Frenc.Polynesia");
            AddCountry("PG", "Pap. New Guinea");
            AddCountry("PH", "Philippines");
            AddCountry("PK", "Pakistan");
            AddCountry("PL", "Poland");
            AddCountry("PM", "St.Pier,Miquel.");
            AddCountry("PN", "Pitcairn Islnds");
            AddCountry("PR", "Puerto Rico");
            AddCountry("PS", "Palestine");
            AddCountry("PT", "Portugal");
            AddCountry("PW", "Palau");
            AddCountry("PY", "Paraguay");
            AddCountry("QA", "Qatar");
            AddCountry("RE", "Reunion");
            AddCountry("RO", "Rumania");
            AddCountry("RS", "Serbia");
            AddCountry("RU", "Russian Fed.");
            AddCountry("RW", "Rwanda");
            AddCountry("SA", "Saudi Arabia");
            AddCountry("SB", "Solomon Islands");
            AddCountry("SC", "Seychelles");
            AddCountry("SD", "Sudan");
            AddCountry("SE", "Sweden");
            AddCountry("SG", "Singapore");
            AddCountry("SH", "St. Helena");
            AddCountry("SI", "Slovenia");
            AddCountry("SJ", "Svalbard");
            AddCountry("SK", "Slovakia");
            AddCountry("SL", "Sierra Leone");
            AddCountry("SM", "San Marino");
            AddCountry("SN", "Senegal");
            AddCountry("SO", "Somalia");
            AddCountry("SR", "Suriname");
            AddCountry("SS", "South Sudan");
            AddCountry("ST", "S.Tome,Principe");
            AddCountry("STL", "Stateless");
            AddCountry("SV", "El Salvador");
            AddCountry("SY", "Syria");
            AddCountry("SZ", "Swaziland");
            AddCountry("TC", "Turksh Caicosin");
            AddCountry("TD", "Chad");
            AddCountry("TF", "French S.Territ");
            AddCountry("TG", "Togo");
            AddCountry("TH", "Thailand");
            AddCountry("TJ", "Tadzhikistan");
            AddCountry("TK", "Tokelau Islands");
            AddCountry("TM", "Turkmenistan");
            AddCountry("TN", "Tunisia");
            AddCountry("TO", "Tonga");
            AddCountry("TP", "East Timor");
            AddCountry("TR", "Turkey");
            AddCountry("TT", "Trinidad,Tobago");
            AddCountry("TV", "Tuvalu");
            AddCountry("TW", "Taiwan");
            AddCountry("TZ", "Tanzania");
            AddCountry("UA", "Ukraine");
            AddCountry("UG", "Uganda");
            AddCountry("UM", "Minor Outl.Isl.");
            AddCountry("US", "USA");
            AddCountry("UY", "Uruguay");
            AddCountry("UZ", "Uzbekistan");
            AddCountry("VA", "Vatican City");
            AddCountry("VC", "St. Vincent");
            AddCountry("VE", "Venezuela");
            AddCountry("VG", "Brit.Virgin Is.");
            AddCountry("VI", "Amer.Virgin Is.");
            AddCountry("VN", "Vietnam");
            AddCountry("VU", "Vanuatu");
            AddCountry("WF", "Wallis,Futuna");
            AddCountry("WS", "Western Samoa");
            AddCountry("XC", "Ceuta");
            AddCountry("XK", "Kosovo");
            AddCountry("XL", "Melilla");
            AddCountry("XM", "Montenegro");
            AddCountry("XS", "Serbien");
            AddCountry("YE", "Yemen");
            AddCountry("YT", "Mayotte");
            AddCountry("YU", "Yugoslavia");
            AddCountry("ZA", "South Africa");
            AddCountry("ZM", "Zambia");
            AddCountry("ZR", "Zaire");
            AddCountry("ZW", "Zimbabwe");
            AddCountry("ZZ", "BDF AG, IHB1");
        }

        private void AddCountry(string key, string name)
        {
            Database.Insert("Countries", new string[] { "Id", "Key", "Name" },
                new string[] { (Guid.NewGuid()).ToString(), key, name });
        }
    }
}
