using System;
using ThinkingHome.Migrator.Framework;

namespace DAL.Migrations
{
    [Migration(202002031319)]
    public class InsertDefaultFieldsSettings : Migration
    {
        public override void Apply()
        {
            InsetDefaultUserSettings("orders",
                "{\"null\":[{\"name\":\"orderCreationDate\",\"displayNameKey\":\"orderCreationDate\",\"type\":\"LocalDateTime\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":true},{\"source\":\"orders\",\"showRawValue\":false,\"name\":\"orderNumber\",\"displayNameKey\":\"orderNumber\",\"type\":\"Link\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":true,\"isReadOnly\":true},{\"name\":\"orderDate\",\"displayNameKey\":\"orderDate\",\"type\":\"Date\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":false},{\"source\":\"orderState\",\"showRawValue\":false,\"name\":\"status\",\"displayNameKey\":\"Order.Status\",\"type\":\"State\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":true},{\"name\":\"shippingDate\",\"displayNameKey\":\"shippingDate\",\"type\":\"Date\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":false},{\"name\":\"deliveryDate\",\"displayNameKey\":\"deliveryDate\",\"type\":\"Date\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":true,\"isReadOnly\":false},{\"source\":\"shippingWarehouses\",\"showRawValue\":false,\"name\":\"shippingWarehouseId\",\"displayNameKey\":\"shippingWarehouseId\",\"type\":\"Select\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":true,\"isReadOnly\":false},{\"source\":\"warehouses\",\"showRawValue\":false,\"name\":\"deliveryWarehouseId\",\"displayNameKey\":\"deliveryWarehouseId\",\"type\":\"Select\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":true,\"isReadOnly\":false},{\"source\":\"shippings\",\"showRawValue\":false,\"name\":\"shippingNumber\",\"displayNameKey\":\"shippingNumber\",\"type\":\"Link\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":true},{\"source\":\"orderShippingStatus\",\"showRawValue\":false,\"name\":\"orderShippingStatus\",\"displayNameKey\":\"orderShippingStatus\",\"type\":\"State\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":true},{\"name\":\"palletsCount\",\"displayNameKey\":\"palletsCount\",\"type\":\"Number\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":false},{\"name\":\"weightKg\",\"displayNameKey\":\"weightKg\",\"type\":\"Number\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":false},{\"source\":\"clients\",\"showRawValue\":false,\"name\":\"clientId\",\"displayNameKey\":\"clientId\",\"type\":\"Select\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":true,\"isReadOnly\":false}]}");

            InsetDefaultUserSettings("shippings",
                "{\"null\":[{\"source\":\"shippings\",\"showRawValue\":false,\"name\":\"shippingNumber\",\"displayNameKey\":\"shippingNumber\",\"type\":\"Link\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":true},{\"source\":\"shippingState\",\"showRawValue\":false,\"name\":\"status\",\"displayNameKey\":\"Shipping.Status\",\"type\":\"State\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":true},{\"source\":\"transportCompanies\",\"showRawValue\":false,\"name\":\"carrierId\",\"displayNameKey\":\"carrierId\",\"type\":\"Select\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":false},{\"source\":\"provider\",\"showRawValue\":false,\"name\":\"providerId\",\"displayNameKey\":\"providerId\",\"type\":\"Select\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":false},{\"source\":\"shippingPoolingState\",\"showRawValue\":false,\"name\":\"poolingStatus\",\"displayNameKey\":\"Pooling.State\",\"type\":\"State\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":true},{\"name\":\"palletsCount\",\"displayNameKey\":\"palletsCount\",\"type\":\"Number\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":false},{\"name\":\"weightKg\",\"displayNameKey\":\"weightKg\",\"type\":\"Number\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":false},{\"source\":\"vehicleTypes\",\"showRawValue\":false,\"name\":\"vehicleTypeId\",\"displayNameKey\":\"vehicleTypeId\",\"type\":\"Select\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":false},{\"name\":\"totalDeliveryCost\",\"displayNameKey\":\"totalDeliveryCost\",\"type\":\"Number\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":false},{\"source\":\"tarifficationType\",\"showRawValue\":false,\"name\":\"tarifficationType\",\"displayNameKey\":\"tarifficationType\",\"type\":\"Enum\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":false},{\"name\":\"driver\",\"displayNameKey\":\"driver\",\"type\":\"Text\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":false},{\"name\":\"vehicleNumber\",\"displayNameKey\":\"vehicleNumber\",\"type\":\"Text\",\"isDefault\":true,\"isFixedPosition\":false,\"isRequired\":false,\"isReadOnly\":false}]}");
        }

        private void InsetDefaultUserSettings(string key, string value)
        {
            Database.Insert("UserSettings", new [] { "Id","UserId", "Key", "Value" },
                new [] { Guid.NewGuid().ToString(), null, key, value });
        }
    }
}